[workspace]
resolver = "2"
members = ["crates/vox-trust-core", "crates/vox-trust-wasm", "crates/vox-trust-cli"]

[workspace.package]
version = "0.2.0"
edition = "2021"
rust-version = "1.94"
license = "Apache-2.0"
repository = "https://github.com/vox-trust/vox-trust"
authors = ["Roger Oliveira"]
homepage = "https://vox-trust.github.io"

[profile.release]
opt-level = "s"
lto = true
codegen-units = 1
panic = "abort"
strip = true
